name: Upload Form Data

on:
  push:
    branches:
      - seance5-test-unitaire
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install pytest
          pip install pytest-html
          pip install flake8


      - name: Lint code with Flake8
        run: |
          flake8 . --count --max-line-length=130 --statistics

      # Étape 4 : Exécuter les tests Pytest
      - name: Run Pytest
        run: |
          pytest --html=tests/rapport/rapport.html --self-contained-html

      # Étape 5 : Sauvegarder le rapport des tests
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-rapport
          path: tests/rapport/rapport.html