name: Upload Form Data

on:
  push:
    branches:
      - seance_4
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install pytest
          pip install flake8

      # Étape 4 : Lancer les tests
      - name: Run tests
        run: |
          if [ -f "tests/test_app.py" ]; then
            pytest
          else
            echo "No tests found. Skipping test step."
          fi